### ISSUE TITLE
MaryTTS

### ISSUE THREAD

**Issue by builderjer** [OpenVoiceOS/ovos-tts-plugin-marytts#5]
MaryTTS does not seem to load correctly.  Mentioned in chats [here](https://matrix.to/#/!jJZwwvVxEHnkiAnlRv:matrix.org/$ljco-StXSmxJrIUxuLZwSmoq4IcHrBZzQ7W-U6EUHGE?via=matrix.org&via=kde.org)

**Comment by JarbasAl** [comment]
is this still an issue?

**Comment by builderjer** [comment]
I really don't know. The only thing I saw in the chats was where I was trying to connect to my mimic3 server with the marytts plugin. With the mimic3 plugin, it makes this out of date I think

**Comment by builderjer** [comment]
I am closing with the above comment
